name: Checking code style

on:
  workflow_call:

jobs:
  code-style:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js LTS version
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Linters and prettier
      run: |
        npm run lint
        echo "Linting finished";
